### ISSUE TITLE
Import error with object pager

### ISSUE THREAD

**Issue by Sergic** [gakuzzzz/play2-pager#4]
Hi there problem
i have an error "object pager is not a member of package jp.t2v.lab.play2"
scalaversion 2.11.7
sbt 0.13.8
scalikejdbc 2.2.+
and i have "jp.t2v" %% "play2-auth" % "0.14.1"
http://joxi.ru/ZrJO6aJTaXzamj
Is it a bug or did I do something wrong?

**Comment by gakuzzzz** [comment]
Sorry late reply.

mmm, Is there play2-pager dependency?

```
"jp.t2v" %% "play2-pager" % "0.1.0"
```

Or,  Do you forget `sbt reaload` ?

**Comment by Sergic** [comment]
Oh, never mind. I've restarted Play Framework activator console and problem have gone. Sorry for bother you

**Comment by gakuzzzz** [comment]
I'm glad to solve your problem :)
